version: '2.2'

services:
  es01:
    container_name: es01
    image: rade9094/elasticsearch:7.6.2
    environment:
      - TZ=Asia/Bahrain
      - node.name=es01
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - ELASTIC_PASSWORD=admin@123 
      - KIBANA_PASSWORD=admin@123
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      #- xpack.license.self_generated.type=trial 
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01.key
      - xpack.security.http.ssl.certificate_authorities=certs/ca.crt
      - xpack.security.http.ssl.certificate=certs/es01.crt
      ##########################################################
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.certificate_authorities=certs/ca.crt
      - xpack.security.transport.ssl.certificate=certs/es01.crt
      - xpack.security.transport.ssl.key=certs/es01.key
    volumes: ['data01:/usr/share/elasticsearch/data']
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: curl --cacert ./config/certs/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
 
  kibana:
    image: rade9094/kibana:7.6.2
    container_name: kibana
    environment:
      - TZ=Asia/Bahrain
      - ELASTICSEARCH_USERNAME="elastic"
      - ELASTICSEARCH_PASSWORD="admin@123"
      - ELASTICSEARCH_HOSTS="https://es01:9200"
      - SERVER_SSL_ENABLED="true"
      - SERVER_SSL_CERTIFICATE="config/certs/kibana.crt"
      - SERVER_SSL_KEY="config/certs/kibana.key"
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES="config/certs/ca.crt"
      - ELASTICSEARCH_SSL_VERIFICATIONMODE="full"
    ports:
      - "5601:5601"
    depends_on:
      - es01

volumes:
  data01:
