version: '3.7'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - node.name=elastic
      - discovery.seed_hosts=elastic
      - cluster.initial_master_nodes=elastic
      - ELASTIC_PASSWORD=admin@123
      - KIBANA_PASSWORD=admin@123
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      #- xpack.license.self_generated.type=trial
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=privkey1.pem
      - xpack.security.http.ssl.certificate_authorities=fullchain1.pem
      - xpack.security.http.ssl.certificate=fullchain1.pem
      ##########################################################
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.certificate_authorities=fullchain1.pem
      - xpack.security.transport.ssl.certificate=fullchain1.pem
      - xpack.security.transport.ssl.key=privkey1.pem
    stop_grace_period: 5m
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - /etc/letsencrypt/archive/metrics.ettrak.com/privkey1.pem:/usr/share/elasticsearch/config/privkey1.pem
      - /etc/letsencrypt/archive/metrics.ettrak.com/fullchain1.pem:/usr/share/elasticsearch/config/fullchain1.pem
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    restart: on-failure

volumes:
  grafana-storage:
  esdata:
